### ISSUE TITLE
gulp build failed

### ISSUE THREAD

**Issue by geomartino** [cvmtl/cvmtl-webui#27]
/Users/geomartino/GitProjects/cvmtl-webui/node_modules/mapbox-gl/node_modules/unflowify/index.js:10
  options = Object.assign({}, defaultOptions, options);
                   ^
TypeError: undefined is not a function
    at unflowify (/Users/geomartino/GitProjects/cvmtl-webui/node_modules/mapbox-gl/node_modules/unflowify/index.js:10:20)
    at nr (/Users/geomartino/GitProjects/cvmtl-webui/node_modules/browserify/node_modules/module-deps/index.js:299:23)
    at /Users/geomartino/GitProjects/cvmtl-webui/node_modules/browserify/node_modules/resolve/lib/async.js:45:21
    at ondir (/Users/geomartino/GitProjects/cvmtl-webui/node_modules/browserify/node_modules/resolve/lib/async.js:188:31)
    at /Users/geomartino/GitProjects/cvmtl-webui/node_modules/browserify/node_modules/resolve/lib/async.js:154:39
    at onex (/Users/geomartino/GitProjects/cvmtl-webui/node_modules/browserify/node_modules/resolve/lib/async.js:94:22)
    at /Users/geomartino/GitProjects/cvmtl-webui/node_modules/browserify/node_modules/resolve/lib/async.js:25:18
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by ajmas** [comment]
Do an install of mapbox-gl from the mapbox-gl repo. Will use mapbox-gl 0.29 when available. See:

https://github.com/mapbox/mapbox-gl-js/issues/3772

**Comment by geomartino** [comment]
Thank you Andre.  Do you still have the display issue?  Which chat platform are you on (skype, hangout, slack)?  So it wll be simplier to talk about this project...

**Comment by ajmas** [comment]
All the above.

**Comment by codelf** [comment]
Martin, je t'ai ajouté au groupe slack CVMTL.

**Comment by geomartino** [comment]
André:  peux-tu me guider un peu svp afin que je puisse déployer le projet en local.  J'ai récupérer le repo de mapbox-gl et lancer un npm install --save mapbox-gl.  par contre le gulp build me donne la même erreur...

**Comment by ajmas** [comment]
En attendant, le version 0.29, il faudra faire:

```
npm install https://github.com/mapbox/mapbox-gl-js.git
```
